ExamWeb_NguyenThienKhang/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExamWeb_NguyenThienKhang.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) :
base(options)
        {
        }
        public DbSet<Phim> phims { set; get; }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {


            modelBuilder.Entity<Phim>().HasData(
        new Phim { Id = 1, TuaDe = "Chúng ta của 8 năm sau", DienVien = "Khang", TrongNuoc = true, GiaVe = 100000, ThoiLuong = 100 },
        new Phim { Id = 2, TuaDe = "Gặp em ngày nắng", DienVien = "Duy", TrongNuoc = false, GiaVe = 200000, ThoiLuong = 110 },
        new Phim { Id = 3, TuaDe = "Không ngạy cưới", DienVien = "Huân", TrongNuoc = true, GiaVe = 500000, ThoiLuong = 500 },
        new Phim { Id = 4, TuaDe = "Gia đình đại chiến", DienVien = "Phát", TrongNuoc = false, GiaVe = 900000, ThoiLuong = 120 },
        new Phim { Id = 5, TuaDe = "Tây du ký", DienVien = "Nam", TrongNuoc = true, GiaVe = 700000, ThoiLuong = 250 },
        new Phim { Id = 6, TuaDe = "Gián điệp", DienVien = "Thông", TrongNuoc = true, GiaVe = 600000, ThoiLuong = 100 },
        new Phim { Id = 7, TuaDe = "Cuộc chiến nhân tâm", DienVien = "Tú", TrongNuoc = true, GiaVe = 105000, ThoiLuong = 100 }

       );
        }
    }
}

ExamWeb_NguyenThienKhang/Models/ErrorViewModel.cs
using System;

namespace ExamWeb_NguyenThienKhang.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ExamWeb_NguyenThienKhang/Models/Phim.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ExamWeb_NguyenThienKhang.Models
{
    public class Phim
    {
        public int Id { get; set; }
        [StringLength(250)]

        [Required(ErrorMessage ="Chưa nhập tựa đề")]
        public string TuaDe { get; set; }

        [StringLength(250)]

        [Required(ErrorMessage = "Chưa nhập tên điễn viên")]
        public string DienVien { get; set; }

        public bool TrongNuoc { get; set; }

        [Range(0, double.MaxValue, ErrorMessage = "Giá vé phải là số không âm.")]
        public double GiaVe { get; set; }


        [Range(60, 180, ErrorMessage = "Thời gian từ 60 đến 180")]
        public int ThoiLuong { get; set; }

    }
}

ExamWeb_NguyenThienKhang/Controllers/HomeController.cs
using ExamWeb_NguyenThienKhang.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ExamWeb_NguyenThienKhang.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ExamWeb_NguyenThienKhang/Controllers/PhimController.cs
using ExamWeb_NguyenThienKhang.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExamWeb_NguyenThienKhang.Controllers
{
    public class PhimController : Controller
    {
        private readonly ApplicationDbContext _db;
        public PhimController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var listPhim = _db.phims.ToList();
            var tong = _db.phims.Sum(x => x.GiaVe);
            ViewBag.SUM = tong;
            return View(listPhim);
        }
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(Phim phim)
        {
            if (ModelState.IsValid)
            {
                _db.phims.Add(phim);
                _db.SaveChanges();
         
            
          TempData["success"] = "Thêm phim thành công";
                return RedirectToAction("Index");
            }
            return View();
        }
        //Hiển thị form cập nhật chủng loại
        public IActionResult Update(int id)
        {
            var phims = _db.phims.Find(id);
            if (phims == null)
            {
                return NotFound();
            }
            return View(phims);
        }
        // Xử lý cập nhật chủng loại
        [HttpPost]
        public IActionResult Update(Phim phim)
        {
            if (ModelState.IsValid) //kiem tra hop le
            {
                //cập nhật category vào table Categories
                _db.phims.Update(phim);
                _db.SaveChanges();
                TempData["success"] = "Cập nhật phim thành công";
                return RedirectToAction("Index");
            }
            return View();
        }
        //Hiển thị form xác nhận xóa chủng loại
        public IActionResult Delete(int id)
        {
            var p = _db.phims.FirstOrDefault(x => x.Id == id);
            if (p == null)
            {
                return NotFound();
            }
            return View(p);
        }
        // Xử lý xóa chủng loại
        public IActionResult DeleteConfirmed(int id)
        {
            var category = _db.phims.Find(id);
            if (category == null)
            {
                return NotFound();
            }
            _db.phims.Remove(category);
            _db.SaveChanges();
            TempData["success"] = "Xoá phim thành công";
            return RedirectToAction("Index");
        }
    }
}

ExamWeb_NguyenThienKhang/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ExamWeb_NguyenThienKhang/Views/Phim/Add.cshtml
@model Phim
<form asp-action="Add" method="post">
    <h2>Thêm mới</h2>
    <hr />
    <div class="form-group">
        <label>Tựa đề</label>

        <input asp-for="TuaDe" class="form-control" />
        <span asp-validation-for="TuaDe" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>Diễn viên</label>
        <input asp-for="DienVien" class="form-control" />
        <span asp-validation-for="DienVien" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="theloai">Thể loại</label>
        <select id="theloai" asp-for="DienVien" class="form-control">
            <option value="trongnuoc">Trong nước</option>
            <option value="nuocngoai">Nước ngoài</option>
        </select>
        <span asp-validation-for="DienVien" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>Thời lượng</label>
        <input asp-for="ThoiLuong" class="form-control" />
        <span asp-validation-for="ThoiLuong" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>Giá vé</label>
        <input asp-for="GiaVe" class="form-control" />
        <span asp-validation-for="GiaVe" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary"> Save </button>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</form>

ExamWeb_NguyenThienKhang/Views/Phim/Delete.cshtml
@model Phim
<form asp-action="DeleteConfirmed" method="post">
    <input type="hidden" asp-for="Id" />
    <h2>Confirm to Delete Phim</h2>
    <hr />
    <div class="form-group">
        <label>Tựa đề</label>
        <input asp-for="TuaDe" disabled class="form-control" />
    </div>
    <div class="form-group">
        <label>Diễn viên</label>

        <input asp-for="DienVien" disabled class="form-control" />
    </div>
    <button type="submit" class="btn btn-danger"> Delete </button>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</form>

ExamWeb_NguyenThienKhang/Views/Phim/Index.cshtml
@model List<Phim>
<partial name="_Notification" />
<div class="row">
    <div class="col-md-6">
        <h2>LIST Phim</h2>
    </div>
    <div class="col-md-6 text-right">
        <a asp-action="Add" class="btn btn-primary">
            <i class="bi bi-plus-circle-fill"></i> Add New
        </a>
    </div>
</div>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Tựa đề</th>
            <th>Thể loại</th>
            <th> Giá Vé </th>
            <th> Thời lượng </th>
            <th> Action </th>

        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model)
        {
        <tr>
            <td>@x.TuaDe</td>
            <td>@(x.TrongNuoc?"Trong nước":"Người nước")</td>
            <td>@String.Format("{0:n0} ₫",x.GiaVe)</td>
            <td>@x.ThoiLuong</td>

            <td>
                <a asp-action="Update" asp-route-id="@x.Id" class="btn btn-success">
                    <i class="bi bi-pencil-square"></i> Edit
                </a>
                <a asp-action="Delete" asp-route-id="@x.Id" class="btn btn-danger">
                    <i class="bi bi-trash"></i> Delete
                </a>
            </td>
        </tr>
        }
    </tbody>
</table>
<div class="alert alert-info pt-2" >
    có tổng tiền<b>@ViewBag.SUM</b>

</div>

ExamWeb_NguyenThienKhang/Views/Phim/Update.cshtml
@model Phim
<form asp-action="Update" method="post">
    <input type="hidden" asp-for="Id" />
    <h2>Cập nhật thông tin Phim</h2>
    <hr />
    <div class="form-group">
        <label>Tựa đề</label>
        <input asp-for="TuaDe" class="form-control" />
        <span asp-validation-for="TuaDe" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>Diễn viên</label>
        <input asp-for="DienVien" class="form-control" />
        <span asp-validation-for="DienVien" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="theloai">Thể loại</label>
        <select id="theloai" asp-for="DienVien" class="form-control">
            <option value="trongnuoc">Trong nước</option>
            <option value="nuocngoai">Nước ngoài</option>
        </select>
        <span asp-validation-for="DienVien" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>Thời lượng</label>
        <input asp-for="ThoiLuong" class="form-control" />
        <span asp-validation-for="ThoiLuong" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>Gía vé</label>
        <input asp-for="GiaVe" class="form-control" />
        <span asp-validation-for="GiaVe" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary"> Update </button>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</form>

ExamWeb_NguyenThienKhang/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExamWeb_NguyenThienKhang</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ExamWeb_NguyenThienKhang</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Phim" asp-action="Index">Phim</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ExamWeb_NguyenThienKhang - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ExamWeb_NguyenThienKhang/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
Swal.fire({
title: "@TempData["success"]",
text: "You clicked the button!",
icon: "success"
});
    </script>
}
@if (TempData["error"] != null)
{
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
Swal.fire({
title: "@TempData["error"]",
text: "You clicked the button!",
icon: "error"
});
    </script>
}